# [".oh-my-zsh/custom/themes/powerlevel10k"]
#     type = "archive"
#     url = "https://github.com/romkatv/powerlevel10k/archive/v1.15.0.tar.gz"
#     exact = true
#     stripComponents = 1
# # [".oh-my-zsh"]
#     type = "archive"
#     url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
#     exact = false
#     stripComponents = 0
#     refreshPeriod = "168h"
